bump indirect syn dep to 2.0.117
Fixes a build error:
	error: failed to select a version for `syn`.
	    ... required by package `wasm-bindgen-macro-support v0.2.108`
	    ... which satisfies dependency `wasm-bindgen-macro-support = "=0.2.108"` (locked to 0.2.108) of package `wasm-bindgen-macro v0.2.108`
	    ... which satisfies dependency `wasm-bindgen-macro = "=0.2.108"` (locked to 0.2.108) of package `wasm-bindgen v0.2.108`
	    ... which satisfies dependency `wasm-bindgen = "^0.2.108"` (locked to 0.2.108) of package `gifski v1.34.0 (/home/aissen/dev/slackanim/gifski)`
	versions that meet the requirements `^2.0` (locked to 2.0.114) are: 2.0.114

	all possible versions conflict with previously selected packages.

	  previously selected package `syn v2.0.110`
	    ... which satisfies dependency `syn = "^2.0"` (locked to 2.0.110) of package `bindgen v0.72.1`
	    ... which satisfies dependency `bindgen = "^0.72"` (locked to 0.72.1) of package `ffmpeg-sys-next v8.0.1`
	    ... which satisfies dependency `ffmpeg-sys-next = "^8.0.0"` (locked to 8.0.1) of package `ffmpeg-next v8.0.0`
	    ... which satisfies dependency `ffmpeg = "^8"` (locked to 8.0.0) of package `gifski v1.34.0 (/home/aissen/dev/slackanim/gifski)`

	failed to select a version for `syn` which could resolve this conflict